package com.taskmanager.ai.controller;

import com.taskmanager.ai.dto.AIBreakdownRequest;
import com.taskmanager.ai.dto.AIDescriptionRequest;
import com.taskmanager.ai.dto.AIStatusRequest;
import com.taskmanager.ai.dto.ChatRequest;
import com.taskmanager.ai.dto.ChatResponse;
import com.taskmanager.ai.service.AITaskService;
import com.taskmanager.api.dto.GetTaskResponse;
import com.taskmanager.service.TaskService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * AI Task Controller — exposes AI-powered endpoints for task management.
 *
 * <p><b>Feature 1:</b> POST /ai/task/generate-description
 * <ul>
 *   <li>User provides a task title.</li>
 *   <li>Ollama (Llama 3.2 1B) generates a professional, detailed description.</li>
 * </ul>
 *
 * <p><b>Feature 2:</b> POST /ai/task/suggest-status
 * <ul>
 *   <li>User provides a task title and description.</li>
 *   <li>LLM analyses context and returns a structured JSON status suggestion.</li>
 * </ul>
 *
 * <p><b>Feature 3:</b> GET /ai/task/summarize
 * <ul>
 *   <li>Fetches all tasks from PostgreSQL via {@link TaskService}.</li>
 *   <li>Injects them as plain text into the LLM prompt (RAG pattern).</li>
 *   <li>Returns a 5-point executive summary of the current project state.</li>
 * </ul>
 *
 * <p><b>Feature 4:</b> POST /ai/task/breakdown
 * <ul>
 *   <li>User provides a complex task title and description.</li>
 *   <li>LLM decomposes it into 5–7 actionable subtasks (Chain-of-Thought prompting).</li>
 *   <li>Each subtask is independently completable in 1–2 hours.</li>
 * </ul>
 *
 * <p><b>Feature 5:</b> POST /ai/task/chat
 * <ul>
 *   <li>User sends a natural-language question about their tasks.</li>
 *   <li>All tasks are fetched and injected as context (RAG + Conversational AI).</li>
 *   <li>Returns a {@link ChatResponse} with the LLM answer and tasks-analyzed count.</li>
 * </ul>
 *
 * <p>Security: Bearer JWT required. Accessible by USER and ADMIN roles.
 */
@RestController
@RequestMapping("/ai/task")
@RequiredArgsConstructor
@Slf4j
@SecurityRequirement(name = "Bearer Authentication")
@Tag(name = "AI Task Services", description = "AI-powered task management features using Ollama (Llama 3.2 1B)")
public class AITaskController {

    private final AITaskService aiTaskService;
    private final TaskService taskService;

    /**
     * Feature 1: AI Task Description Generator.
     *
     * <p>Accepts a task title and returns a professional 3-4 sentence description
     * generated by the locally running LLM via prompt engineering.
     *
     * <p><b>AI Pattern:</b> Prompt Engineering
     * <p><b>Model:</b> Ollama Llama 3.2 1B (runs locally — no external API calls)
     *
     * @param request contains the task title
     * @return AI-generated task description
     */
    @PreAuthorize("hasAnyRole('USER', 'ADMIN')")
    @PostMapping(
            path = "/generate-description",
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.TEXT_PLAIN_VALUE)
    @Operation(
            summary = "AI: Generate task description from title",
            description = "Provide a task title — the AI generates a professional 3-4 sentence description "
                    + "covering what needs to be done, why it matters, and acceptance criteria. "
                    + "Uses Prompt Engineering with Ollama Llama 3.2 1B running locally.")
    public ResponseEntity<String> generateDescription(
            @Valid @RequestBody AIDescriptionRequest request) {

        log.info("POST /ai/task/generate-description — title: {}", request.getTitle());
        String description = aiTaskService.generateDescription(request.getTitle());
        return ResponseEntity.ok(description);
    }

    /**
     * Feature 2: AI Status Suggester.
     *
     * <p>Accepts a task title and description, and returns a JSON object containing
     * the most appropriate status and a brief reason, generated by the local LLM.
     *
     * <p><b>AI Pattern:</b> Structured JSON Output — the prompt constrains the
     * model to respond only with {@code {"status": "...", "reason": "..."}} so the
     * caller can parse it directly.
     *
     * <p><b>Valid statuses:</b> {@code TODO} · {@code IN_PROGRESS} · {@code DONE} · {@code BLOCKED}
     *
     * <p><b>Model:</b> Ollama Llama 3.2 1B (runs locally — no external API calls)
     *
     * @param request contains the task title and description
     * @return JSON string: {@code {"status": "TODO", "reason": "..."}}
     */
    @PreAuthorize("hasAnyRole('USER', 'ADMIN')")
    @PostMapping(
            path = "/suggest-status",
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(
            summary = "AI: Suggest task status from title and description",
            description = "Provide a task title and description — the AI analyses the context and returns "
                    + "the most appropriate status (TODO / IN_PROGRESS / DONE / BLOCKED) plus a brief reason. "
                    + "Demonstrates Structured JSON Output from Ollama Llama 3.2 1B running locally. "
                    + "Response format: {\"status\": \"TODO\", \"reason\": \"...\"}.")
    public ResponseEntity<String> suggestStatus(
            @Valid @RequestBody AIStatusRequest request) {

        log.info("POST /ai/task/suggest-status — title: {}", request.getTitle());
        String suggestion = aiTaskService.suggestStatus(request.getTitle(), request.getDescription());
        return ResponseEntity.ok(suggestion);
    }

    /**
     * Feature 3: AI Task Summarizer — RAG Pattern.
     *
     * <p>Fetches all tasks from the database, injects them as context into the LLM prompt,
     * and returns a concise executive summary covering project health, completed work,
     * in-progress items, blockers, and recommended next actions.
     *
     * <p><b>AI Pattern:</b> RAG (Retrieval-Augmented Generation) — the most important
     * AI pattern. The LLM has no direct DB access; tasks are fetched first and injected
     * as plain text so the model reasons over <em>live data</em>, not hallucinations.
     *
     * <p><b>Model:</b> Ollama Llama 3.2 1B (runs locally — no external API calls)
     *
     * @return AI-generated 5-point executive summary of all tasks
     */
    @PreAuthorize("hasAnyRole('USER', 'ADMIN')")
    @GetMapping(
            path = "/summarize",
            produces = MediaType.TEXT_PLAIN_VALUE)
    @Operation(
            summary = "AI: Executive summary of all tasks (RAG pattern)",
            description = "Fetches all tasks from PostgreSQL and injects them into the LLM context. "
                    + "Returns a 5-point executive summary: project health, completed work, "
                    + "work in progress, blockers/risks, and recommended next actions. "
                    + "Demonstrates the RAG (Retrieval-Augmented Generation) pattern with Ollama Llama 3.2 1B.")
    public ResponseEntity<String> summarizeAllTasks() {
        log.info("GET /ai/task/summarize — fetching all tasks for AI summarization");
        List<GetTaskResponse> allTasks = taskService.getAllTasks();
        String summary = aiTaskService.summarizeAllTasks(allTasks);
        return ResponseEntity.ok(summary);
    }

    /**
     * Feature 4: AI Task Breakdown — Chain-of-Thought Prompting.
     *
     * <p>Accepts a complex task title and description, and returns a numbered list
     * of 5–7 specific, actionable subtasks generated by the local LLM.
     * Each subtask has a clear action verb and a specific deliverable completable
     * in 1–2 hours — ideal for sprint planning and story-point estimation.
     *
     * <p><b>AI Pattern:</b> Chain-of-Thought Prompting — the prompt instructs the model
     * to reason step-by-step and decompose work into granular, independently testable units.
     *
     * <p><b>Model:</b> Ollama Llama 3.2 1B (runs locally — no external API calls)
     *
     * @param request contains the complex task title and description
     * @return numbered plain-text list of 5–7 subtasks
     */
    @PreAuthorize("hasAnyRole('USER', 'ADMIN')")
    @PostMapping(
            path = "/breakdown",
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.TEXT_PLAIN_VALUE)
    @Operation(
            summary = "AI: Break a complex task into 5–7 actionable subtasks",
            description = "Provide a complex task title and description — the AI decomposes it into "
                    + "5–7 specific, independently completable subtasks, each taking 1–2 hours. "
                    + "Demonstrates Chain-of-Thought Prompting with Ollama Llama 3.2 1B running locally.")
    public ResponseEntity<String> breakdownTask(
            @Valid @RequestBody AIBreakdownRequest request) {

        log.info("POST /ai/task/breakdown — title: {}", request.getTitle());
        String breakdown = aiTaskService.breakdownTask(request.getTitle(), request.getDescription());
        return ResponseEntity.ok(breakdown);
    }

    /**
     * Feature 5: AI Conversational Chatbot — RAG + Conversational AI.
     *
     * <p>Accepts a natural-language question (e.g. <em>"What should I work on next?"</em>
     * or <em>"Are there any blocked tasks?"</em>), fetches all tasks from the database,
     * injects them as context, and returns the LLM's answer together with the number
     * of tasks that were analysed.
     *
     * <p><b>AI Pattern:</b> Conversational AI + RAG — the LLM is grounded in live
     * task data and explicitly instructed to answer using <em>only</em> that data.
     *
     * <p><b>Model:</b> Ollama Llama 3.2 1B (runs locally — no external API calls)
     *
     * @param request contains the user's natural-language question
     * @return {@link ChatResponse} with {@code reply} and {@code tasksAnalyzed}
     */
    @PreAuthorize("hasAnyRole('USER', 'ADMIN')")
    @PostMapping(
            path = "/chat",
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(
            summary = "AI: Conversational assistant over live task data (RAG + Conversational AI)",
            description = "Send a natural-language question about your tasks — e.g. 'How many tasks are "
                    + "IN_PROGRESS?' or 'Are there any blockers?'. All tasks are fetched from PostgreSQL "
                    + "and injected as context so the LLM answers from live data only. "
                    + "Returns the reply and how many tasks were analysed.")
    public ResponseEntity<ChatResponse> chat(
            @Valid @RequestBody ChatRequest request) {

        log.info("POST /ai/task/chat — message: {}", request.getMessage());
        List<GetTaskResponse> allTasks = taskService.getAllTasks();
        ChatResponse response = aiTaskService.chat(request.getMessage(), allTasks);
        return ResponseEntity.ok(response);
    }
}

