package com.taskmanager.ai.controller;

import com.taskmanager.ai.dto.AIDescriptionRequest;
import com.taskmanager.ai.dto.AIStatusRequest;
import com.taskmanager.ai.service.AITaskService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * AI Task Controller — exposes AI-powered endpoints for task management.
 *
 * <p><b>Feature 1:</b> POST /ai/task/generate-description
 * <ul>
 *   <li>User provides a task title.</li>
 *   <li>Ollama (Llama 3.2 1B) generates a professional, detailed description.</li>
 * </ul>
 *
 * <p><b>Feature 2:</b> POST /ai/task/suggest-status
 * <ul>
 *   <li>User provides a task title and description.</li>
 *   <li>LLM analyses context and returns a structured JSON status suggestion.</li>
 * </ul>
 *
 * <p>Security: Bearer JWT required. Accessible by USER and ADMIN roles.
 */
@RestController
@RequestMapping("/ai/task")
@RequiredArgsConstructor
@Slf4j
@SecurityRequirement(name = "Bearer Authentication")
@Tag(name = "AI Task Services", description = "AI-powered task management features using Ollama (Llama 3.2 1B)")
public class AITaskController {

    private final AITaskService aiTaskService;

    /**
     * Feature 1: AI Task Description Generator.
     *
     * <p>Accepts a task title and returns a professional 3-4 sentence description
     * generated by the locally running LLM via prompt engineering.
     *
     * <p><b>AI Pattern:</b> Prompt Engineering
     * <p><b>Model:</b> Ollama Llama 3.2 1B (runs locally — no external API calls)
     *
     * @param request contains the task title
     * @return AI-generated task description
     */
    @PreAuthorize("hasAnyRole('USER', 'ADMIN')")
    @PostMapping(
            path = "/generate-description",
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.TEXT_PLAIN_VALUE)
    @Operation(
            summary = "AI: Generate task description from title",
            description = "Provide a task title — the AI generates a professional 3-4 sentence description "
                    + "covering what needs to be done, why it matters, and acceptance criteria. "
                    + "Uses Prompt Engineering with Ollama Llama 3.2 1B running locally.")
    public ResponseEntity<String> generateDescription(
            @Valid @RequestBody AIDescriptionRequest request) {

        log.info("POST /ai/task/generate-description — title: {}", request.getTitle());
        String description = aiTaskService.generateDescription(request.getTitle());
        return ResponseEntity.ok(description);
    }

    /**
     * Feature 2: AI Status Suggester.
     *
     * <p>Accepts a task title and description, and returns a JSON object containing
     * the most appropriate status and a brief reason, generated by the local LLM.
     *
     * <p><b>AI Pattern:</b> Structured JSON Output — the prompt constrains the
     * model to respond only with {@code {"status": "...", "reason": "..."}} so the
     * caller can parse it directly.
     *
     * <p><b>Valid statuses:</b> {@code TODO} · {@code IN_PROGRESS} · {@code DONE} · {@code BLOCKED}
     *
     * <p><b>Model:</b> Ollama Llama 3.2 1B (runs locally — no external API calls)
     *
     * @param request contains the task title and description
     * @return JSON string: {@code {"status": "TODO", "reason": "..."}}
     */
    @PreAuthorize("hasAnyRole('USER', 'ADMIN')")
    @PostMapping(
            path = "/suggest-status",
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(
            summary = "AI: Suggest task status from title and description",
            description = "Provide a task title and description — the AI analyses the context and returns "
                    + "the most appropriate status (TODO / IN_PROGRESS / DONE / BLOCKED) plus a brief reason. "
                    + "Demonstrates Structured JSON Output from Ollama Llama 3.2 1B running locally. "
                    + "Response format: {\"status\": \"TODO\", \"reason\": \"...\"}.")
    public ResponseEntity<String> suggestStatus(
            @Valid @RequestBody AIStatusRequest request) {

        log.info("POST /ai/task/suggest-status — title: {}", request.getTitle());
        String suggestion = aiTaskService.suggestStatus(request.getTitle(), request.getDescription());
        return ResponseEntity.ok(suggestion);
    }
}

