package com.taskmanager.ai.dto;

import lombok.Builder;
import lombok.Getter;

/**
 * Response DTO for Feature 5: AI Conversational Chatbot.
 *
 * <p>Wraps the LLM reply together with a metadata count of how many tasks
 * were injected into the context, making the RAG scope transparent to the caller.
 */
@Getter
@Builder
public class ChatResponse {

    /** The natural-language answer generated by the LLM. */
    private String reply;

    /** Number of tasks injected into the LLM context (RAG scope transparency). */
    private int tasksAnalyzed;
}

